### ISSUE TITLE
rebindinterval causes segfault

### ISSUE THREAD

**Issue by kortemik** [rsyslog/librelp#64] opened 2017-09-27 14:59 UTC
```
action
(
        type="omrelp"
        name="hostname.dom.ain"
        target="a.b.c.d"
        port="601"
        queue.size="3276800"
        queue.type="Disk"
        queue.checkpointinterval="65536"
        queue.filename="rsyslog_imrelp_queue"
        queue.maxfilesize="128m"
        queue.saveonshutdown="on"
        queue.syncqueuefiles="off"
        queue.maxdiskspace="25g"
        action.ResumeInterval="15"
        action.ResumeRetryCount="-1"
        rebindinterval="128"
)
```
gdb output
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe186b700 (LWP 20390)]
0x00007ffff6c54834 in relpCltHintBurstEnd (pThis=0x7fffd0009d00) at relpclt.c:371
371     relpclt.c: No such file or directory.
(gdb) bt full
#0  0x00007ffff6c54834 in relpCltHintBurstEnd (pThis=0x7fffd0009d00) at relpclt.c:371
No locals.
#1  0x00007ffff2dffecf in endTransaction (pWrkrData=0x7fffd00020f0) at omrelp.c:518
        iRet = RS_RET_OK
#2  0x00005555555d4105 in actionTryCommit (pThis=0x555555853fa0, pWti=0x555555857430) at ../action.c:1225
        iRet = RS_RET_OK
#3  0x00005555555d434f in actionCommit (pThis=0x555555853fa0, pWti=0x555555857430) at ../action.c:1311
        bDone = 0 '\000'
        iRet = RS_RET_OK
#4  0x00005555555d47d9 in processBatchMain (pVoid=0x555555853fa0, pBatch=0x555555857468, pWti=0x555555857430) at ../action.c:1421
        pAction = 0x555555853fa0
        i = 2
        ttNow = {timeType = 32 ' ', month = 97 'a', day = 0 '\000', hour = -28 '\344', minute = -1 '\377', second = 127 '\177', secfracPrecision = 0 '\000', OffsetMinute = 0 '\000', OffsetHour = 112 'p', OffsetMode = -85 '\253', year = 0, secfrac = 32767, 
          inUTC = 48 '0'}
        iRet = RS_RET_OK
#5  0x00005555555c5226 in ConsumerReg (pThis=0x555555854530, pWti=0x555555857430) at queue.c:2005
        iCancelStateSave = 1
        bNeedReLock = 1
        skippedMsgs = 0
        iRet = RS_RET_OK
        __PRETTY_FUNCTION__ = "ConsumerReg"
#6  0x00005555555c017b in wtiWorker (pThis=0x555555857430) at wti.c:365
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {140736977090304, 8905112294871272873, 1, 140736977091008, 140736977090304, 140737018618144, 8905112294713986473, 3368756044716314025}, __mask_was_saved = 0}}, __pad = {0x7fffe186ac90, 0x0, 0x0, 0x0}}
        __cancel_routine = 0x5555555bfd2e <wtiWorkerCancelCleanup>
        __cancel_arg = 0x555555857430
        __not_first_call = 0
        pWtp = 0x555555857280
        pAction = 0x0
        bInactivityTOOccured = 0
        localRet = RS_RET_IDLE
        terminateRet = RS_RET_OK
        wrkrInfo = 0x0
        iCancelStateSave = 0
        i = 32767
        j = -511267584
        k = 0
        iRet = RS_RET_OK
#7  0x00005555555bebb7 in wtpWorker (arg=0x555555857430) at wtp.c:410
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {140736977090304, 8905112294917410217, 1, 140736977091008, 140736977090304, 140737018618144, 8905112294877564329, 3368756060526611881}, __mask_was_saved = 0}}, __pad = {0x7fffe186adf0, 0x0, 0x0, 0x0}}
        __cancel_routine = 0x5555555be775 <wtpWrkrExecCancelCleanup>
        __cancel_arg = 0x555555857430
        __not_first_call = 0
        pWti = 0x555555857430
        pThis = 0x555555857280
        sigSet = {__val = {1048576, 0 <repeats 15 times>}}
        pszDbgHdr = 0x5555558573d0 "hostname.dom.ain queue:Reg"
        thrdName = "rs:jtylogsvip02.jty.op-\000\000\000\000\000\000\000\000"
        __PRETTY_FUNCTION__ = "wtpWorker"
#8  0x00007ffff79b0dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#9  0x00007ffff635128d in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by rgerhards** [comment] 2017-09-28 16:58
looks like a duplicate of https://github.com/rsyslog/librelp/issues/64

**Comment by rgerhards** [comment] 2017-09-28 16:59
looks like a duplicate of https://github.com/rsyslog/rsyslog/issues/120

**Comment by rgerhards** [comment] 2017-09-29 10:01
It's actually a bug in rsyslog's omrelp, not in librelp itself. Solution is available in https://github.com/rsyslog/rsyslog/issues/120

So closing this issue here.

**Closed by rgerhards** 2017-09-29 10:01 UTC
